### ISSUE TITLE
v0.1.9 bug

### ISSUE THREAD

**Issue by unparalleled-ysj** [Masao-Someki/espnet_onnx#32]
When I tested the demo of ljspeech, I encountered the following problems

`Traceback (most recent call last):
  File "export2onnx.py", line 6, in <module>
    m.export_from_pretrained(tag_name)
  File "/work/ysj/espnet_onnx/espnet_onnx/export/tts/export_tts.py", line 109, in export_from_pretrained
    self.export(model, tag_name, quantize)
  File "/work/ysj/espnet_onnx/espnet_onnx/export/tts/export_tts.py", line 64, in export
    self._export_tts(tts_model, export_dir, verbose)
  File "/work/ysj/espnet_onnx/espnet_onnx/export/tts/export_tts.py", line 174, in _export_tts
    self._export_model(model, verbose, path)
  File "/work/ysj/espnet_onnx/espnet_onnx/export/tts/export_tts.py", line 163, in _export_model
    dynamic_axes=model.get_dynamic_axes(),
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/onnx/__init__.py", line 320, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/onnx/utils.py", line 707, in _export
    _set_opset_version(opset_version)
  File "/root/anaconda3/envs/espnet/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 849, in _set_opset_version
    raise ValueError("Unsupported ONNX opset version: " + str(opset_version))
ValueError: Unsupported ONNX opset version: 15`

My pytorch version is 1.10.1, is it related to this?

**Comment by unparalleled-ysj** [comment]
Yes, the bug is related to the pytorch version

**Comment by v-yunbin** [comment]
> Yes, the bug is related to the pytorch version

which  pytorch version can avoid this bug?

**Comment by unparalleled-ysj** [comment]
> > Yes, the bug is related to the pytorch version
> 
> which pytorch version can avoid this bug? my torch version 1.8.1 met same bug.

torch.version >= 1.11
